### ISSUE TITLE
Vampric Knowledge & Unholy Teachings DO NOT Display their skills. [FABRIC 1.20.1]

### ISSUE THREAD

**Issue by Caliburnt** [nvb-uy/Death_Knights#1]
In my modded server and my own personal game, my friends and I have tried several times to see if we can get the Death Knight skills to work, where only the FROST skills seem to be working. Here's a screenshot with the examples:

![Screenshot 2024-08-28 002947](https://github.com/user-attachments/assets/0ce247fa-b299-4f8b-a7f5-30f1dced05c0)
![Screenshot 2024-08-28 002939](https://github.com/user-attachments/assets/8e809815-c260-4903-9b45-eef0f3531f6e)

For reference, while we're playing with a lot of other mods, we're playing with some of the following other mods:
- Better Combat
- Combat Roll
- ALL of the RPG series mods
- ALL of the MORE RPG series mods
- Trinkets
- Artifacts
- Knight Quest
- Epic Knights Mod

Thank you for your time regardless.

**Comment by nvb-uy** [comment]
As seen in the mod's page, blood and unholy death knights are not implemented in 0.3.0
