### ISSUE TITLE
Death Knights Mod does not function in Prominence II Modpack

### ISSUE THREAD

**Issue by Schism989** [nvb-uy/Death_Knights#2]
As I noticed that the mod appears linked to the Prominence modpack's wiki, I thought I'd mention this.

When using Prominence Modpack in it's current state as of August 30th 2024, the game crashes on start-up when trying to run it with the Death Knights mod, version 0.3.1. This occurs whether I've downloaded it via curseforge or manually from the zip on modrinth. I imagine this is why it's not included in the modpack quite yet, but I thought I'd add the issue here both to raise awareness to the issue if it was not discovered already, and to notify others who may attempt to download the mod with the modpack.

It, however, functions fine when downloaded on a mod profile on its own with only its dependencies, so it appears something may be conflicting with the DK mod that causes the crash on startup. Below is the code the launcher provides when I attempt to run the game with the Death Knights mod, with no other additional mods being installed

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'death_knights'!"

How to Reproduce:

1. Install Prominence II RPG Modpack for version 1.20.1
2. Install Death Knights version 0.3.1
3. Launch Game

**Comment by nvb-uy** [comment]
Known, please wait until Hasturian Era releases.
