### ISSUE TITLE
Does not use semver

### ISSUE THREAD

**Issue by Poopooracoocoo** [nvb-uy/Death_Knights#7]
Users see the following warnings in their log:
`[ForkJoinPool-1-worker-9/WARN]: Mod death_knights uses the version 0.6.1beta which isn't compatible with Loader's extended semantic version format (Could not parse version number component '1beta'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version`

Tested with https://modrinth.com/mod/death-knights/version/0.6.1beta

Valid semver would be `0.6.1-beta`

https://semver.org/

**Comment by nvb-uy** [comment]
future updates (starting from 1.0.0) will not include any text so it'll be semver-compliant
